# .github/ci.yml
#
# Test Buildkite Plugin
# Github Actions Workflow
#
# @author lelia

# workflow name
name: CI

# replaces webhook
on:
  [ push ]

# list of actions
jobs:
  # action name
  lint:
    # runs-on: -> agents: queue:
    runs-on: ubuntu-18.04
    # steps: -> steps:
    steps:
    # uses: -> plugins:
    - uses: actions/checkout@v2
    # name: -> label:
    - name: âœ¨ lint
    # run: -> command:
      run: echo "Running linting"
    # name: -> label:
    - name: ğŸš shellcheck
    # run: -> command:
      run: echo "Running shellcheck"

  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: ğŸ³ tests
      run: echo "Running tests"
