# .github/ci.yml
#
# Test Buildkite Plugin
# Github Actions Workflow
#
# @author lelia

# workflow name
name: CI

# replaces webhook
on:
  [ push ]

# list of actions
jobs:

  # action name
  lint:

    # runs-on: -> agents: queue:
    runs-on: ubuntu-18.04

    # steps: -> steps:
    steps:

    # name: -> label:
    - name: âœ¨ lint
    # uses: -> plugins:
      uses: actions/checkout@v2
    # run: -> command:
      run: docker-compose run --rm lint

    # name: -> label:
    - name: ğŸš shellcheck
    # uses: -> plugins:
      uses: ludeeus/action-shellcheck@0.2.1

  test:
    runs-on: ubuntu-18.04
    steps:
    - name: ğŸ³ tests
      run: docker-compose run --rm tests
      uses: actions/checkout@v2
