# Test Buildkite Plugin
# Github Actions Workflow

name: CI

on:
  [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: âœ¨ lint
        run: docker-compose run --rm lint

  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: ğŸš shellcheck
        uses: ludeeus/action-shellcheck@0.4.0


  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: ğŸ³ tests
        run: docker-compose run --rm tests
