# .github/ci.yml
#
# Test Buildkite Plugin
# Github Actions Workflow
#
# @author lelia

# workflow name
name: CI

# replaces webhook
on:
  [ push,pull_request ]
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      
    - name: âœ¨ lint
      run: docker-compose run --rm lint

    - name: ğŸš shellcheck
      uses: ludeeus/action-shellcheck@0.2.1
      with:
        ignore: tests # can be removed since shellcheck should ignore bats regardless
        
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: ğŸ³ tests
      run: docker-compose run --rm tests
      
# Wait + kick off workflows
